# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    	./desktop.nix
	./common.nix
    ];
  networking.hostName = "AarniLoota";
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4844fc67-e51d-4192-abfc-2ee8ef7e68d9";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/0F53-C8B7";
      fsType = "vfat";
    };

  swapDevices = [ ];
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;
 users.users.aarni.packages = with pkgs; [
		(lib.hiPrio gcc)
		(lib.lowPrio clang)
		android-studio
		bear
		texlive.combined.scheme-full
		mangohud
		gamemode
		binutils
		clang-tools
		cmake
		ctags
		thunderbird
		freecad
		patchelf
		luajit
    gnuplot
		rr
    pandoc
		rustup
		quick-lint-js
		gdb
		octaveFull
		git-quick-stats
		openrgb
		gnumake
		meson
		wf-recorder
		ncspot
		mpv
		ninja
		ulauncher
		acpi
		glib
		mpv
		tectonic
		element-desktop

		

 ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
